// ─────────────────────────────────────────────────────────────
// SHIFTS
// Three academic bus shifts for Madhav Enterprise Transport Portal
// ─────────────────────────────────────────────────────────────
export const SHIFTS = [
  {
    id: "7:30",
    label: "Early Shift",
    time: "7:30 AM",
    emoji: "🌥️",
  },
  {
    id: "9:30",
    label: "Morning Shift",
    time: "9:30 AM",
    emoji: "☀️",
  },
  {
    id: "10:30",
    label: "Afternoon Shift",
    time: "10:30 AM",
    emoji: "🌤️",
  },
];

// ─────────────────────────────────────────────────────────────
// DEPARTMENTS
// Default shift per department:
//   Diploma courses  → 7:30 AM
//   B.Tech courses   → 9:30 AM
//   Commerce / BBA / BCA / MBA → 10:30 AM
// ─────────────────────────────────────────────────────────────
export const DEPARTMENTS = [
  // ── Diploma (7:30 AM) ──────────────────────────────────────
  { id: "diploma-it",    label: "Diploma – Information Technology",       defaultShift: "7:30" },
  { id: "diploma-cs",    label: "Diploma – Computer Science",             defaultShift: "7:30" },
  { id: "diploma-ec",    label: "Diploma – Electronics & Communication",  defaultShift: "7:30" },
  { id: "diploma-me",    label: "Diploma – Mechanical Engineering",       defaultShift: "7:30" },
  { id: "diploma-civil", label: "Diploma – Civil Engineering",            defaultShift: "7:30" },
  { id: "diploma-ee",    label: "Diploma – Electrical Engineering",       defaultShift: "7:30" },

  // ── B.Tech (9:30 AM) ──────────────────────────────────────
  { id: "btech-it",    label: "B.Tech – Information Technology",          defaultShift: "9:30" },
  { id: "btech-cs",    label: "B.Tech – Computer Science",                defaultShift: "9:30" },
  { id: "btech-ec",    label: "B.Tech – Electronics & Communication",     defaultShift: "9:30" },
  { id: "btech-me",    label: "B.Tech – Mechanical Engineering",          defaultShift: "9:30" },
  { id: "btech-civil", label: "B.Tech – Civil Engineering",               defaultShift: "9:30" },
  { id: "btech-ee",    label: "B.Tech – Electrical Engineering",          defaultShift: "9:30" },
  { id: "msc-it",      label: "M.Sc – Information Technology",            defaultShift: "9:30" },
  { id: "mca",         label: "MCA – Master of Computer Applications",    defaultShift: "9:30" },

  // ── Commerce / Management (10:30 AM) ─────────────────────
  { id: "bcom",        label: "B.Com – Bachelor of Commerce",             defaultShift: "10:30" },
  { id: "bcom-ca",     label: "B.Com – Computer Application",             defaultShift: "10:30" },
  { id: "bcom-honors", label: "B.Com (Honors)",                           defaultShift: "10:30" },
  { id: "bba",         label: "BBA – Bachelor of Business Administration",defaultShift: "10:30" },
  { id: "bca",         label: "BCA – Bachelor of Computer Application",   defaultShift: "10:30" },
  { id: "mba",         label: "MBA – Master of Business Administration",  defaultShift: "10:30" },
];

// ─────────────────────────────────────────────────────────────
// YEARS & SEMESTERS
// 4 years × 2 semesters = 8 semesters total.
// autoSemester: the semester that is system-assigned when a
//   student selects that year (cannot be changed manually).
// ─────────────────────────────────────────────────────────────
export const YEARS = [
  {
    value: "1",
    label: "First Year",
    autoSemester: "Semester 1-2",
    semesters: [
      { value: "Semester 1-2", label: "Semester 1 - 2" },
    ],
  },
  {
    value: "2",
    label: "Second Year",
    autoSemester: "Semester 3-4",
    semesters: [
      { value: "Semester 3-4", label: "Semester 3 - 4" },
    ],
  },
  {
    value: "3",
    label: "Third Year",
    autoSemester: "Semester 5-6",
    semesters: [
      { value: "Semester 5-6", label: "Semester 5 - 6" },
    ],
  },
  {
    value: "4",
    label: "Fourth Year",
    autoSemester: "Semester 7-8",
    semesters: [
      { value: "Semester 7-8", label: "Semester 7 - 8" },
    ],
  },
];

// ─────────────────────────────────────────────────────────────
// PICKUP POINTS & FEES
// ─────────────────────────────────────────────────────────────
export const PICKUP_POINTS = [
  { id: "UNDERA", label: "UNDERA", fee: 21000, time: "7:30 AM" },
  { id: "PANCHVATI", label: "PANCHVATI", fee: 21000, time: "7:30 AM" },
  { id: "SAHYOG", label: "SAHYOG", fee: 21000, time: "7:30 AM" },
  { id: "GORWA ITI", label: "GORWA ITI", fee: 21000, time: "7:30 AM" },
  { id: "DASHAMA CHOKDI", label: "DASHAMA CHOKDI", fee: 21000, time: "7:30 AM" },
  { id: "ACHARYA NURSING HOME", label: "ACHARYA NURSING HOME", fee: 21000, time: "7:30 AM" },
  { id: "JAIN MANDIR (HIGH TENSION)", label: "JAIN MANDIR (HIGH TENSION)", fee: 21000, time: "7:30 AM" },
  { id: "GOLDEN SILVER", label: "GOLDEN SILVER", fee: 21000, time: "7:30 AM" },
  { id: "ELLORA PARK", label: "ELLORA PARK", fee: 21000, time: "7:30 AM" },
  { id: "INOX", label: "INOX", fee: 21000, time: "7:30 AM" },
  { id: "NATUBHAI CIRCLE", label: "NATUBHAI CIRCLE", fee: 21000, time: "7:30 AM" },
  { id: "CHAKLI CIRCLE", label: "CHAKLI CIRCLE", fee: 21000, time: "7:30 AM" },
  { id: "PIZZA INN", label: "PIZZA INN", fee: 21000, time: "7:30 AM" },
  { id: "VALLABH CHOWK", label: "VALLABH CHOWK", fee: 21000, time: "7:30 AM" },
  { id: "HAVELI", label: "HAVELI", fee: 21000, time: "7:30 AM" },
  { id: "URMI CIRCLE", label: "URMI CIRCLE", fee: 21000, time: "7:30 AM" },
  { id: "GAI CIRCLE", label: "GAI CIRCLE", fee: 21000, time: "7:30 AM" },
  { id: "AKOTA STADIUM", label: "AKOTA STADIUM", fee: 21000, time: "7:30 AM" },
  { id: "MUNJMAHUDA", label: "MUNJMAHUDA", fee: 21000, time: "7:30 AM" },
  { id: "GUJARAT TRACTOR", label: "GUJARAT TRACTOR", fee: 21000, time: "7:30 AM" },
  { id: "MANISHA CHOWKDI", label: "MANISHA CHOWKDI", fee: 21000, time: "7:30 AM" },
  { id: "GAJANAND COMPLEX", label: "GAJANAND COMPLEX", fee: 21000, time: "7:30 AM" },
  { id: "DEV DEEP", label: "DEV DEEP", fee: 21000, time: "7:30 AM" },
  { id: "AKANKSHA DUPLEX", label: "AKANKSHA DUPLEX", fee: 21000, time: "7:30 AM" },
  { id: "PAVANDHAM", label: "PAVANDHAM", fee: 21000, time: "7:30 AM" },
  { id: "SAMTA POLICE STATION", label: "SAMTA POLICE STATION", fee: 21000, time: "7:30 AM" },
  { id: "ZANSI KI RANI", label: "ZANSI KI RANI", fee: 21000, time: "7:30 AM" },
  { id: "RAJESH TOWER", label: "RAJESH TOWER", fee: 21000, time: "7:30 AM" },
  { id: "NANDALAY", label: "NANDALAY", fee: 21000, time: "7:30 AM" },
  { id: "HARINAGAR WATER TANK", label: "HARINAGAR WATER TANK", fee: 21000, time: "7:30 AM" },
  { id: "PRATHAM COMPLEX", label: "PRATHAM COMPLEX", fee: 21000, time: "7:30 AM" },
  { id: "SWAMINARAYAN MANDIR", label: "SWAMINARAYAN MANDIR", fee: 21000, time: "7:30 AM" },
  { id: "NARAYAN GARDEN", label: "NARAYAN GARDEN", fee: 21000, time: "7:30 AM" },
  { id: "RAMESHWAR CHOKDI", label: "RAMESHWAR CHOKDI", fee: 21000, time: "7:30 AM" },
  { id: "YASH COMPLEX", label: "YASH COMPLEX", fee: 21000, time: "7:30 AM" },
  { id: "BANSAL MALL - GOTRI", label: "BANSAL MALL - GOTRI", fee: 21000, time: "7:30 AM" },
  { id: "THE NEST", label: "THE NEST", fee: 21000, time: "7:30 AM" },
  { id: "APEXA PARK", label: "APEXA PARK", fee: 21000, time: "7:30 AM" },
  { id: "KALA GHODA", label: "KALA GHODA", fee: 21000, time: "7:30 AM" },
  { id: "RANESHWAR PETROL PUMP", label: "RANESHWAR PETROL PUMP", fee: 21000, time: "7:30 AM" },
  { id: "TAKSH COMPLEX", label: "TAKSH COMPLEX", fee: 21000, time: "7:30 AM" },
  { id: "BRIGHT SCHOOL (BHAILY)", label: "BRIGHT SCHOOL (BHAILY)", fee: 21000, time: "7:30 AM" },
  { id: "PANCHMUKHI HANUMAN MANDIR", label: "PANCHMUKHI HANUMAN MANDIR", fee: 21000, time: "7:30 AM" },
  { id: "VASNA JAKAT NAKA", label: "VASNA JAKAT NAKA", fee: 21000, time: "7:30 AM" },
  { id: "KALYAN PARTY PLOT", label: "KALYAN PARTY PLOT", fee: 21000, time: "7:30 AM" },
  { id: "PATRAKAR", label: "PATRAKAR", fee: 21000, time: "7:30 AM" },
  { id: "JP POLICE STATION NEW", label: "JP POLICE STATION NEW", fee: 21000, time: "7:30 AM" },
  { id: "SUN PHARMA SBI", label: "SUN PHARMA SBI", fee: 21000, time: "7:30 AM" },
  { id: "VAD GARDEN", label: "VAD GARDEN", fee: 21000, time: "7:30 AM" },
  { id: "AKSHAR CHOWK", label: "AKSHAR CHOWK", fee: 21000, time: "7:30 AM" },
  { id: "BANCO", label: "BANCO", fee: 21000, time: "7:30 AM" },
  { id: "NARAYAN VADI", label: "NARAYAN VADI", fee: 21000, time: "7:30 AM" },
  { id: "KHATI AMBLI", label: "KHATI AMBLI", fee: 21000, time: "7:30 AM" },
  { id: "ATLADRA MANDIR", label: "ATLADRA MANDIR", fee: 21000, time: "7:30 AM" },
  { id: "TRANSPEK (KHISKOLI)", label: "TRANSPEK (KHISKOLI)", fee: 21000, time: "7:30 AM" },
  { id: "KALALI 3 RASTA", label: "KALALI 3 RASTA", fee: 21000, time: "7:30 AM" },
  { id: "CHHANI TP-13", label: "CHHANI TP-13", fee: 21000, time: "7:30 AM" },
  { id: "FIREBRIGADE", label: "FIREBRIGADE", fee: 21000, time: "7:30 AM" },
  { id: "PRAYAG CHOKDI", label: "PRAYAG CHOKDI", fee: 21000, time: "7:30 AM" },
  { id: "KEYA MOTORS", label: "KEYA MOTORS", fee: 21000, time: "7:30 AM" },
  { id: "CHHANI JAKAT NAKA", label: "CHHANI JAKAT NAKA", fee: 21000, time: "7:30 AM" },
  { id: "MILITARY BOYS HOSTEL", label: "MILITARY BOYS HOSTEL", fee: 21000, time: "7:30 AM" },
  { id: "MEHSANA NAGAR CIRCLE", label: "MEHSANA NAGAR CIRCLE", fee: 21000, time: "7:30 AM" },
  { id: "DELUX CROSSING", label: "DELUX CROSSING", fee: 21000, time: "7:30 AM" },
  { id: "SAMA TALAV", label: "SAMA TALAV", fee: 21000, time: "7:30 AM" },
  { id: "PUNIT NAGAR", label: "PUNIT NAGAR", fee: 21000, time: "7:30 AM" },
  { id: "JALARAM MANDIR", label: "JALARAM MANDIR", fee: 21000, time: "7:30 AM" },
  { id: "CHANAKYAPURI", label: "CHANAKYAPURI", fee: 21000, time: "7:30 AM" },
  { id: "SWATI SOC.", label: "SWATI SOC.", fee: 17000, time: "7:30 AM" },
  { id: "ABHILASHA CHOKDI", label: "ABHILASHA CHOKDI", fee: 21000, time: "7:30 AM" },
  { id: "GHELANI PETROL PUMP", label: "GHELANI PETROL PUMP", fee: 21000, time: "7:30 AM" },
  { id: "FATEHGUNJ POST OFFICE", label: "FATEHGUNJ POST OFFICE", fee: 21000, time: "7:30 AM" },
  { id: "FATEHGUNJ PETROL PUMP", label: "FATEHGUNJ PETROL PUMP", fee: 21000, time: "7:30 AM" },
  { id: "SAFFRON TOWER", label: "SAFFRON TOWER", fee: 21000, time: "7:30 AM" },
  { id: "L&T CIRCLE", label: "L&T CIRCLE", fee: 21000, time: "7:30 AM" },
  { id: "BRIGHT SCHOOL (KARELIBAUG)", label: "BRIGHT SCHOOL (KARELIBAUG)", fee: 21000, time: "7:30 AM" },
  { id: "AMIT NAGAR CIRCLE", label: "AMIT NAGAR CIRCLE", fee: 21000, time: "7:30 AM" },
  { id: "GADA CIRCLE (HARNI)", label: "GADA CIRCLE (HARNI)", fee: 21000, time: "7:30 AM" },
  { id: "AIRPORT CIRCLE", label: "AIRPORT CIRCLE", fee: 21000, time: "7:30 AM" },
  { id: "SAIDEEP NAGAR", label: "SAIDEEP NAGAR", fee: 21000, time: "7:30 AM" },
  { id: "KHODIYAR NAGAR", label: "KHODIYAR NAGAR", fee: 21000, time: "7:30 AM" },
  { id: "SUPER BAKERY", label: "SUPER BAKERY", fee: 21000, time: "7:30 AM" },
  { id: "SARDAR ESTATE", label: "SARDAR ESTATE", fee: 21000, time: "7:30 AM" },
  { id: "KRISHNA PARK", label: "KRISHNA PARK", fee: 21000, time: "7:30 AM" },
  { id: "JEEVAN BHARTI SCHOOL", label: "JEEVAN BHARTI SCHOOL", fee: 21000, time: "7:30 AM" },
  { id: "MUKTANAND", label: "MUKTANAND", fee: 21000, time: "7:30 AM" },
  { id: "AMRAPALI", label: "AMRAPALI", fee: 21000, time: "7:30 AM" },
  { id: "AMBALAL PARK", label: "AMBALAL PARK", fee: 21000, time: "7:30 AM" },
  { id: "KARELIBAUG WATER TANK", label: "KARELIBAUG WATER TANK", fee: 21000, time: "7:30 AM" },
  { id: "SANGAM CHAR RASTA", label: "SANGAM CHAR RASTA", fee: 21000, time: "7:30 AM" },
  { id: "ASHIRWAD SOC.", label: "ASHIRWAD SOC.", fee: 21000, time: "7:30 AM" },
  { id: "MOTINAGAR", label: "MOTINAGAR", fee: 21000, time: "7:30 AM" },
  { id: "KISHANWADI CHAR RASTA", label: "KISHANWADI CHAR RASTA", fee: 21000, time: "7:30 AM" },
  { id: "MAHAVIR HALL", label: "MAHAVIR HALL", fee: 21000, time: "7:30 AM" },
  { id: "NAVJEEVAN", label: "NAVJEEVAN", fee: 21000, time: "7:30 AM" },
  { id: "VINAY SOC.", label: "VINAY SOC.", fee: 21000, time: "7:30 AM" },
  { id: "KAMLANAGAR", label: "KAMLANAGAR", fee: 21000, time: "7:30 AM" },
  { id: "YOGESWAR TOWNSHIP", label: "YOGESWAR TOWNSHIP", fee: 21000, time: "7:30 AM" },
  { id: "AJWA CHOKDI", label: "AJWA CHOKDI", fee: 21000, time: "7:30 AM" },
  { id: "BADAMDIBAUG", label: "BADAMDIBAUG", fee: 20000, time: "7:30 AM" },
  { id: "NEHRU BHAVAN", label: "NEHRU BHAVAN", fee: 20000, time: "7:30 AM" },
  { id: "BAGIKHANA/TOP", label: "BAGIKHANA/TOP", fee: 20000, time: "7:30 AM" },
  { id: "VRUNDAVAN CHAR RASTA", label: "VRUNDAVAN CHAR RASTA", fee: 20000, time: "7:30 AM" },
  { id: "BAPOD JAKAT NAKA", label: "BAPOD JAKAT NAKA", fee: 20000, time: "7:30 AM" },
  { id: "VAIKUNTH - 1", label: "VAIKUNTH - 1", fee: 20000, time: "7:30 AM" },
  { id: "WAGHODIA CHOWKDI", label: "WAGHODIA CHOWKDI", fee: 20000, time: "7:30 AM" },
  { id: "UMA CHAR RASTA", label: "UMA CHAR RASTA", fee: 20000, time: "7:30 AM" },
  { id: "RADHIKA BHAVAN", label: "RADHIKA BHAVAN", fee: 20000, time: "7:30 AM" },
  { id: "AYURVEDIC 3 RASTA", label: "AYURVEDIC 3 RASTA", fee: 20000, time: "7:30 AM" },
  { id: "SHREE RANG VIDHYALAYA", label: "SHREE RANG VIDHYALAYA", fee: 20000, time: "7:30 AM" },
  { id: "KALADARSHAN", label: "KALADARSHAN", fee: 20000, time: "7:30 AM" },
  { id: "PARIVAR CHAR RASTA", label: "PARIVAR CHAR RASTA", fee: 20000, time: "7:30 AM" },
  { id: "RUKSHMANI PARTY PLOT", label: "RUKSHMANI PARTY PLOT", fee: 20000, time: "7:30 AM" },
  { id: "GURUKUL", label: "GURUKUL", fee: 20000, time: "7:30 AM" },
  { id: "TIRTHAK", label: "TIRTHAK", fee: 20000, time: "7:30 AM" },
  { id: "MAHESH NAGAR", label: "MAHESH NAGAR", fee: 20000, time: "7:30 AM" },
  { id: "SOMA TALAV", label: "SOMA TALAV", fee: 20000, time: "7:30 AM" },
  { id: "M.M.VORA AUTOMOBILES", label: "M.M.VORA AUTOMOBILES", fee: 20000, time: "7:30 AM" },
  { id: "KAPURAI CHOWKDI", label: "KAPURAI CHOWKDI", fee: 20000, time: "7:30 AM" },
  { id: "DAWAT", label: "DAWAT", fee: 17000, time: "7:30 AM" },
  { id: "DEEP CHAMBER", label: "DEEP CHAMBER", fee: 17000, time: "7:30 AM" },
  { id: "INDRA COMPLEX", label: "INDRA COMPLEX", fee: 17000, time: "7:30 AM" },
  { id: "BHAVAN'S VIDHYALAYA", label: "BHAVAN'S VIDHYALAYA", fee: 17000, time: "7:30 AM" },
  { id: "VADSAR BRIDGE", label: "VADSAR BRIDGE", fee: 17000, time: "7:30 AM" },
  { id: "GAYATRI MANDIR", label: "GAYATRI MANDIR", fee: 17000, time: "7:30 AM" },
  { id: "GIDC TANK (ALWANAKA)", label: "GIDC TANK (ALWANAKA)", fee: 17000, time: "7:30 AM" },
  { id: "JUPITER CROSSING", label: "JUPITER CROSSING", fee: 17000, time: "7:30 AM" },
  { id: "BANKER HOSPITAL", label: "BANKER HOSPITAL", fee: 17000, time: "7:30 AM" },
  { id: "SAI CHOWKDI", label: "SAI CHOWKDI", fee: 17000, time: "7:30 AM" },
  { id: "DARBAR CHOWKDI", label: "DARBAR CHOWKDI", fee: 17000, time: "7:30 AM" },
  { id: "SUN CITY CIRCLE", label: "SUN CITY CIRCLE", fee: 17000, time: "7:30 AM" },
  { id: "VRAJDHAM TEMPLE", label: "VRAJDHAM TEMPLE", fee: 17000, time: "7:30 AM" },
  { id: "EVA MALL", label: "EVA MALL", fee: 17000, time: "7:30 AM" },
  { id: "SARASWATI COMPLEX", label: "SARASWATI COMPLEX", fee: 17000, time: "7:30 AM" },
  { id: "TULSIDHAM", label: "TULSIDHAM", fee: 17000, time: "7:30 AM" },
  { id: "KABIR COMPLEX", label: "KABIR COMPLEX", fee: 17000, time: "7:30 AM" },
  { id: "AAKASHWANI", label: "AAKASHWANI", fee: 17000, time: "7:30 AM" },
  { id: "BANSAL MALL - TARSALI", label: "BANSAL MALL - TARSALI", fee: 17000, time: "7:30 AM" },
  { id: "CHANDRA NAGAR", label: "CHANDRA NAGAR", fee: 17000, time: "7:30 AM" },
  { id: "TARSALI MARKET", label: "TARSALI MARKET", fee: 17000, time: "7:30 AM" },
  { id: "DHANIYAVI BRIDGE", label: "DHANIYAVI BRIDGE", fee: 17000, time: "7:30 AM" },
  { id: "GANGA SAGAR", label: "GANGA SAGAR", fee: 17000, time: "7:30 AM" },
  { id: "UNAD DEEP", label: "UNAD DEEP", fee: 17000, time: "7:30 AM" },
  { id: "SUSEN", label: "SUSEN", fee: 17000, time: "7:30 AM" },
  { id: "NOVINO", label: "NOVINO", fee: 17000, time: "7:30 AM" },
  { id: "MAKARPURA HANUMAN MANDIR", label: "MAKARPURA HANUMAN MANDIR", fee: 17000, time: "7:30 AM" },
  { id: "MANEJA CROSSING", label: "MANEJA CROSSING", fee: 17000, time: "7:30 AM" },
  { id: "VOLTAMP", label: "VOLTAMP", fee: 17000, time: "7:30 AM" },
  { id: "GAYATRI NAGAR", label: "GAYATRI NAGAR", fee: 17000, time: "7:30 AM" },
  { id: "PADRA DEPO", label: "PADRA DEPO", fee: 23000, time: "7:30 AM" },
  { id: "SANGMA - PADRA", label: "SANGMA - PADRA", fee: 23000, time: "7:30 AM" },
  { id: "SAMIYALA - PADRA", label: "SAMIYALA - PADRA", fee: 23000, time: "7:30 AM" },
  { id: "SHAKTINATH MAHADEV - BHARUCH", label: "SHAKTINATH MAHADEV - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "SHRAVAN CHOWKDI - BHARUCH", label: "SHRAVAN CHOWKDI - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "NANDELAV BRIDGE - BHARUCH", label: "NANDELAV BRIDGE - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "ABC CHOKDI - BHARUCH", label: "ABC CHOKDI - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "SHITAL CHOKDI - BHARUCH", label: "SHITAL CHOKDI - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "KASAK FUVARA - BHARUCH", label: "KASAK FUVARA - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "JYOTI NAGAR (INOX) - BHARUCH", label: "JYOTI NAGAR (INOX) - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "TULSIDHAM (RADHA KRUSHNA) - BHARUCH", label: "TULSIDHAM (RADHA KRUSHNA) - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "CHAMUNDA MANDIR - BHARUCH", label: "CHAMUNDA MANDIR - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "ZADESHWAR GAM - BHARUCH", label: "ZADESHWAR GAM - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "ZADESHWAR CHOWKDI - BHARUCH", label: "ZADESHWAR CHOWKDI - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "NARMADA CHOWKDI - BHARUCH", label: "NARMADA CHOWKDI - BHARUCH", fee: 48000, time: "7:30 AM" },
  { id: "NABIPUR CHOKDI", label: "NABIPUR CHOKDI", fee: 41500, time: "7:30 AM" },
  { id: "PALEJ CHOKDI", label: "PALEJ CHOKDI", fee: 35500, time: "7:30 AM" },
  { id: "PATEL CHAMBER (CHOKDI) - KARJAN", label: "PATEL CHAMBER (CHOKDI) - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "SWAMINARAYAN MANDIR - KARJAN", label: "SWAMINARAYAN MANDIR - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "BUS DEPO - KARJAN", label: "BUS DEPO - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "JUNI COURT - KARJAN", label: "JUNI COURT - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "PANCHAYAT KACHERI - KARJAN", label: "PANCHAYAT KACHERI - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "MIYAGAM CHOKDI - KARJAN", label: "MIYAGAM CHOKDI - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "ESSAR PUMP - KARJAN", label: "ESSAR PUMP - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "JUNABAJAR HIGHWAY CHOKDI - KARJAN", label: "JUNABAJAR HIGHWAY CHOKDI - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "KANDARI - KARJAN", label: "KANDARI - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "MANGLEGE - KARJAN", label: "MANGLEGE - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "VRUNDAVAN PARK - KARJAN", label: "VRUNDAVAN PARK - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "CHANDRALOK - KARJAN", label: "CHANDRALOK - KARJAN", fee: 21000, time: "7:30 AM" },
  { id: "POR", label: "POR", fee: 18000, time: "7:30 AM" },
  { id: "SADHLI", label: "SADHLI", fee: 29000, time: "7:30 AM" },
  { id: "TIMBARVA - SADHLI", label: "TIMBARVA - SADHLI", fee: 27000, time: "7:30 AM" },
  { id: "LINGSTHALI - SADHLI", label: "LINGSTHALI - SADHLI", fee: 24000, time: "7:30 AM" },
  { id: "KAYAVAROHAN - SADHLI", label: "KAYAVAROHAN - SADHLI", fee: 21000, time: "7:30 AM" },
  { id: "MENPURA - SADHLI", label: "MENPURA - SADHLI", fee: 19500, time: "7:30 AM" },
  { id: "SHINOR CHOKDI", label: "SHINOR CHOKDI", fee: 35000, time: "7:30 AM" },
  { id: "VEGA CHOKDI", label: "VEGA CHOKDI", fee: 35000, time: "7:30 AM" },
  { id: "DABHOI DEPO", label: "DABHOI DEPO", fee: 35000, time: "7:30 AM" },
  { id: "FARTIKUI", label: "FARTIKUI", fee: 35000, time: "7:30 AM" },
  { id: "THUVAVI", label: "THUVAVI", fee: 32000, time: "7:30 AM" },
  { id: "BHILAPUR", label: "BHILAPUR", fee: 29000, time: "7:30 AM" },
  { id: "PALASVADA", label: "PALASVADA", fee: 27000, time: "7:30 AM" },
  { id: "KELANPUR", label: "KELANPUR", fee: 23000, time: "7:30 AM" },
  { id: "LAKODARA", label: "LAKODARA", fee: 29000, time: "7:30 AM" },
  { id: "SAGMA", label: "SAGMA", fee: 23000, time: "7:30 AM" },
  { id: "VADODARA GAS - HARNI", label: "VADODARA GAS - HARNI", fee: 20000, time: "7:30 AM" },
];

