import React, { useState, useEffect, useCallback } from "react";
import {
  Box,
  Avatar,
  Chip,
  CircularProgress,
  IconButton,
  Skeleton,
  TextField,
  Grid,
  Tooltip,
  Autocomplete,
  InputLabel,
} from "@mui/material";
import {
  PrintOutlined,
  PeopleAltOutlined,
  RestartAltOutlined,
  CalendarTodayOutlined,
  EventAvailableOutlined,
  DirectionsBusOutlined,
  SchoolOutlined,
  BadgeOutlined,
  PhoneOutlined,
} from "@mui/icons-material";
import {
  fetchApprovedStudents,
  fetchReceiptForReprint,
  fetchAllDepartments,
  fetchAllPickupPoints,
} from "../../../api/admin/api";
import { useAuth } from "../context/AuthContext";
import ReceiptDialog from "../components/ReceiptDialog";
import EditApprovedStudentModal from "../components/EditApprovedStudentModal";

// ── Helpers ──────────────────────────────────────────────────────
const YEAR_LABEL = {
  1: "1st Year",
  2: "2nd Year",
  3: "3rd Year",
  4: "4th Year",
};
const PAGE_LIMIT = 50;

const fmtDate = (d) => {
  if (!d) return "—";
  const dt = new Date(d);
  return `${String(dt.getDate()).padStart(2, "0")}/${String(dt.getMonth() + 1).padStart(2, "0")}/${dt.getFullYear()}`;
};

// ── Filter Select Styling ─────────────────────────────────────────
const selectSx = {
  minWidth: 160,
  "& .MuiOutlinedInput-root": {
    height: 40,
    borderRadius: "10px",
    fontSize: "0.83rem",
    bgcolor: "#fff",
    "& .MuiOutlinedInput-notchedOutline": { borderColor: "#E2E8F0" },
    "&:hover .MuiOutlinedInput-notchedOutline": { borderColor: "#CBD5E1" },
  },
  "& .MuiInputLabel-root": {
    fontSize: "0.7rem",
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "#94A3B8",
  },
};

// ── Shift format helper ──
const SHIFT_FORMAT_MAP = {
  // Exact stored IDs from DB (generated by backend generateId())
  "1-shift": "1st (07:30 AM)",
  "2-shift": "2nd (09:30 AM)",
  "3-shift": "3rd (11:30 AM)",
  "1st-shift": "1st (07:30 AM)",
  "2nd-shift": "2nd (09:30 AM)",
  "3rd-shift": "3rd (11:30 AM)",
  // Plain ordinal strings
  "1st": "1st (07:30 AM)",
  "2nd": "2nd (09:30 AM)",
  "3rd": "3rd (11:30 AM)",
  // Time-based keys
  "7:30": "1st (07:30 AM)",
  "9:30": "2nd (09:30 AM)",
  "10:30": "3rd (11:30 AM)",
  "11:30": "3rd (11:30 AM)",
};
const formatShift = (shift) => {
  if (!shift) return "";
  // Exact match first
  if (SHIFT_FORMAT_MAP[shift]) return SHIFT_FORMAT_MAP[shift];
  const s = String(shift).toLowerCase();
  // Partial matches — handles "3rd shift", "3-shift-xxxx" (with timestamp suffix), etc.
  if (s.startsWith("1-shift") || s.includes("1st") || s.includes("7:30"))
    return "1st (07:30 AM)";
  if (s.startsWith("2-shift") || s.includes("2nd") || s.includes("9:30"))
    return "2nd (09:30 AM)";
  if (
    s.startsWith("3-shift") ||
    s.includes("3rd") ||
    s.includes("10:30") ||
    s.includes("11:30")
  )
    return "3rd (11:30 AM)";
  return shift;
};

const getShiftColors = (shift) => {
  const s = String(shift || "").toLowerCase();
  if (s.includes("1st") || s.includes("7:30"))
    return { bg: "#EFF6FF", color: "#2563EB", border: "#BFDBFE" };
  if (s.includes("2nd") || s.includes("9:30"))
    return { bg: "#F0FDF4", color: "#15803D", border: "#BBF7D0" };
  if (s.includes("3rd") || s.includes("10:30"))
    return { bg: "#FFF7ED", color: "#C2410C", border: "#FED7AA" };
  return { bg: "#F1F5F9", color: "#475569", border: "#E2E8F0" };
};

// ── Avatar background color from name ──
const getAvatarColor = (name) => {
  const colors = [
    { bg: "#EFF6FF", color: "#2563EB" },
    { bg: "#F0FDF4", color: "#15803D" },
    { bg: "#FDF4FF", color: "#9333EA" },
    { bg: "#FFF7ED", color: "#C2410C" },
    { bg: "#F0F9FF", color: "#0369A1" },
    { bg: "#FFF1F2", color: "#BE123C" },
  ];
  const idx = (name?.charCodeAt(0) || 0) % colors.length;
  return colors[idx];
};

// ═══════════════════════════════════════════════════════════════
export default function ApprovedStudentsPage() {
  const { token } = useAuth();

  // ── Filter state ──────────────────────────────────────────────
  const [year, setYear] = useState("");
  const [department, setDept] = useState("");
  const [route, setRoute] = useState("");
  const [searchName, setSearchName] = useState("");
  const [searchReceipt, setSearchReceipt] = useState("");
  const [searchMobile, setSearchMobile] = useState("");
  const [appliedFilters, setAppliedFilters] = useState({});

  // ── Data state ────────────────────────────────────────────────
  const [students, setStudents] = useState([]);
  const [totalCount, setTotalCount] = useState(0);
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(false);
  const [loading, setLoading] = useState(true);
  const [loadingMore, setLoadingMore] = useState(false);
  const [error, setError] = useState("");

  // ── Filter options fetched from backend ──────────────────────
  const [allDepts, setAllDepts] = useState([]);
  const [allRoutes, setAllRoutes] = useState([]);
  const [optionsLoading, setOptionsLoading] = useState(true);

  useEffect(() => {
    if (!token) return;
    setOptionsLoading(true);
    Promise.all([
      fetchAllDepartments(token).catch(() => ({ departments: [] })),
      fetchAllPickupPoints(token).catch(() => ({ pickupPoints: [] })),
    ])
      .then(([deptRes, routeRes]) => {
        setAllDepts(
          (deptRes.departments || [])
            .filter((d) => d.isActive !== false)
            .map((d) => d.label)
            .filter(Boolean)
            .sort(),
        );
        setAllRoutes(
          (routeRes.pickupPoints || [])
            .filter((p) => p.isActive !== false)
            .map((p) => p.label)
            .filter(Boolean)
            .sort(),
        );
      })
      .finally(() => setOptionsLoading(false));
  }, [token]);

  // ── Modals ────────────────────────────────────────────────────
  const [receiptOpen, setReceiptOpen] = useState(false);
  const [receiptData, setReceiptData] = useState(null);
  const [reprintLoading, setReprintLoading] = useState(null);
  const [editOpen, setEditOpen] = useState(false);
  const [editStudent, setEditStudent] = useState(null);

  const loadStudents = useCallback(
    async (pg = 1, append = false) => {
      if (!token) return;
      append ? setLoadingMore(true) : setLoading(true);
      try {
        const res = await fetchApprovedStudents(token, {
          ...appliedFilters,
          page: pg,
          limit: PAGE_LIMIT,
        });
        if (res.success) {
          setStudents((prev) => (append ? [...prev, ...res.data] : res.data));
          setTotalCount(res.totalCount);
          setHasMore(pg * PAGE_LIMIT < res.totalCount);
          setPage(pg);
        }
      } catch (err) {
        setError(err.message || "Failed to load students");
      } finally {
        append ? setLoadingMore(false) : setLoading(false);
      }
    },
    [token, appliedFilters],
  );

  useEffect(() => {
    loadStudents(1);
  }, [loadStudents]);

  const handleApply = () =>
    setAppliedFilters({
      year,
      department,
      route,
      searchName,
      searchReceipt,
      searchMobile,
    });
  const handleReset = () => {
    setYear("");
    setDept("");
    setRoute("");
    setSearchName("");
    setSearchReceipt("");
    setSearchMobile("");
    setAppliedFilters({});
  };
  const handleLoadMore = () => loadStudents(page + 1, true);

  const handleReprint = async (e, student) => {
    e.stopPropagation();
    setReprintLoading(student.receiptNumber);
    try {
      const res = await fetchReceiptForReprint(token, student.receiptNumber);
      if (res.success && res.receiptData) {
        setReceiptData(res.receiptData);
        setReceiptOpen(true);
      }
    } catch (err) {
      alert("Could not load receipt: " + err.message);
    } finally {
      setReprintLoading(null);
    }
  };

  const handleCardClick = (student) => {
    setEditStudent(student);
    setEditOpen(true);
  };

  const handleEditSaved = (updated) => {
    setEditOpen(false);
    setEditStudent(null);
    setStudents((prev) =>
      prev.map((s) =>
        s._id === updated._id ? { ...s, ...updated, payment: s.payment } : s,
      ),
    );
  };

  return (
    <Box sx={{ maxWidth: 1280 }}>
      {/* Header Section */}
      <Box
        sx={{
          mb: 3,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
          gap: 2,
        }}
      >
        <Box>
          <h1
            style={{
              margin: 0,
              fontSize: "1.55rem",
              fontWeight: 800,
              color: "#0F172A",
            }}
          >
            Approved Students
          </h1>
          <Chip
            label={`${totalCount} STUDENTS APPROVED`}
            size="small"
            icon={<PeopleAltOutlined style={{ fontSize: 13 }} />}
            sx={{
              mt: 0.8,
              height: 22,
              fontSize: "0.68rem",
              fontWeight: 700,
              bgcolor: "#EFF6FF",
              color: "#2563EB",
            }}
          />
        </Box>
      </Box>

      {/* Filter Bar */}
      <Box
        sx={{
          bgcolor: "#fff",
          borderRadius: "14px",
          border: "1px solid #E2E8F0",
          p: 2,
          mb: 3,
        }}
      >
        <Grid container spacing={2} alignItems="flex-end">
          {/* Search Name */}
          <Grid size={{ xs: 12, sm: 6, md: 3 }}>
            <TextField
              size="small"
              fullWidth
              label="Search Name"
              value={searchName}
              onChange={(e) => setSearchName(e.target.value)}
              sx={selectSx}
            />
          </Grid>

          {/* Receipt No */}
          <Grid size={{ xs: 12, sm: 6, md: 3 }}>
            <TextField
              size="small"
              fullWidth
              label="Receipt No"
              value={searchReceipt}
              onChange={(e) => setSearchReceipt(e.target.value)}
              sx={selectSx}
            />
          </Grid>

          {/* Mobile No — student or parent */}
          <Grid size={{ xs: 12, sm: 6, md: 3 }}>
            <TextField
              size="small"
              fullWidth
              type="tel"
              label="Mobile No"
              placeholder="Student or Parent"
              value={searchMobile}
              onChange={(e) => setSearchMobile(e.target.value)}
              sx={selectSx}
            />
          </Grid>

          {/* Department — Autocomplete */}
          <Grid size={{ xs: 12, sm: 6, md: 3 }}>
            <Autocomplete
              size="small"
              fullWidth
              options={allDepts}
              value={department || null}
              onChange={(_, val) => setDept(val || "")}
              loading={optionsLoading}
              loadingText="Loading..."
              clearOnEscape
              renderInput={(params) => (
                <TextField {...params} label="Department" sx={selectSx} />
              )}
              sx={{
                "& .MuiOutlinedInput-root": {
                  height: 40,
                  borderRadius: "10px",
                  fontSize: "0.83rem",
                  bgcolor: "#fff",
                },
              }}
            />
          </Grid>

          {/* Year — Autocomplete */}
          <Grid size={{ xs: 12, sm: 3, md: 3 }}>
            <Autocomplete
              size="small"
              fullWidth
              options={["1", "2", "3", "4"]}
              getOptionLabel={(opt) => YEAR_LABEL[opt] || opt}
              value={year || null}
              onChange={(_, val) => setYear(val || "")}
              clearOnEscape
              renderInput={(params) => (
                <TextField {...params} label="Year" sx={selectSx} />
              )}
              sx={{
                "& .MuiOutlinedInput-root": {
                  height: 40,
                  borderRadius: "10px",
                  fontSize: "0.83rem",
                  bgcolor: "#fff",
                },
              }}
            />
          </Grid>

          {/* Route — Autocomplete */}
          <Grid size={{ xs: 12, sm: 3, md: 3 }}>
            <Autocomplete
              size="small"
              fullWidth
              options={allRoutes}
              value={route || null}
              onChange={(_, val) => setRoute(val || "")}
              loading={optionsLoading}
              loadingText="Loading..."
              clearOnEscape
              renderInput={(params) => (
                <TextField {...params} label="Route" sx={selectSx} />
              )}
              sx={{
                "& .MuiOutlinedInput-root": {
                  height: 40,
                  borderRadius: "10px",
                  fontSize: "0.83rem",
                  bgcolor: "#fff",
                },
              }}
            />
          </Grid>

          {/* Apply */}
          <Grid size={{ xs: 12, sm: 3, md: 2 }}>
            <Box
              onClick={handleApply}
              sx={{
                height: 40,
                px: 3,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                borderRadius: "10px",
                bgcolor: "#2563EB",
                color: "#fff",
                cursor: "pointer",
                fontWeight: 700,
                fontSize: "0.83rem",
                "&:hover": { bgcolor: "#1D4ED8" },
              }}
            >
              Apply
            </Box>
          </Grid>

          {Object.keys(appliedFilters).length > 0 && (
            <Grid size={{ xs: 12, sm: 3, md: 2 }}>
              <Box sx={{ display: "flex", justifyContent: "flex-start" }}>
                <IconButton
                  onClick={handleReset}
                  sx={{ height: 40, width: 40, bgcolor: "#F1F5F9" }}
                >
                  <RestartAltOutlined />
                </IconButton>
              </Box>
            </Grid>
          )}
        </Grid>
      </Box>

      {/* Cards List */}
      <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
        {loading ? (
          // ── Skeleton Cards ──
          [1, 2, 3, 4, 5].map((i) => (
            <Box
              key={i}
              sx={{
                bgcolor: "#fff",
                borderRadius: "16px",
                border: "1px solid #E2E8F0",
                p: { xs: 2, md: 2.5 },
              }}
            >
              <Box
                sx={{ display: "flex", alignItems: "center", gap: 2, mb: 2 }}
              >
                <Skeleton
                  variant="rounded"
                  width={52}
                  height={52}
                  sx={{ borderRadius: "14px", flexShrink: 0 }}
                />
                <Box sx={{ flex: 1 }}>
                  <Skeleton width="40%" height={20} />
                  <Skeleton width="25%" height={14} sx={{ mt: 0.5 }} />
                </Box>
                <Skeleton width={80} height={28} sx={{ borderRadius: "8px" }} />
              </Box>
              <Box
                sx={{
                  display: "grid",
                  gridTemplateColumns: {
                    xs: "1fr 1fr",
                    md: "repeat(4, 1fr) repeat(2, 1fr)",
                  },
                  gap: 2,
                }}
              >
                {[1, 2, 3, 4, 5, 6].map((j) => (
                  <Box key={j}>
                    <Skeleton width="50%" height={12} />
                    <Skeleton width="70%" height={16} sx={{ mt: 0.5 }} />
                  </Box>
                ))}
              </Box>
            </Box>
          ))
        ) : students.length === 0 ? (
          <Box
            sx={{
              py: 10,
              textAlign: "center",
              color: "#94A3B8",
              bgcolor: "#fff",
              borderRadius: "16px",
              border: "1px solid #E2E8F0",
            }}
          >
            <PeopleAltOutlined sx={{ fontSize: 48, opacity: 0.3, mb: 1 }} />
            <p style={{ margin: 0, fontWeight: 600, fontSize: "1rem" }}>
              No students found
            </p>
            <p style={{ margin: "4px 0 0", fontSize: "0.83rem" }}>
              Try adjusting your filters
            </p>
          </Box>
        ) : (
          students.map((s) => {
            const shiftColors = getShiftColors(s.shift);
            const avatarColors = getAvatarColor(s.fullName);
            const isReprintLoading = reprintLoading === s.receiptNumber;

            return (
              <Box
                key={s._id || s.receiptNumber}
                onClick={() => handleCardClick(s)}
                sx={{
                  bgcolor: "#fff",
                  borderRadius: "16px",
                  border: "1px solid #E2E8F0",
                  p: { xs: 2, md: 2.5 },
                  cursor: "pointer",
                  transition: "all 0.22s cubic-bezier(0.4, 0, 0.2, 1)",
                  position: "relative",
                  overflow: "hidden",
                  "&::before": {
                    content: '""',
                    position: "absolute",
                    left: 0,
                    top: 0,
                    bottom: 0,
                    width: "4px",
                    bgcolor: shiftColors.color,
                    opacity: 0,
                    transition: "opacity 0.22s ease",
                    borderRadius: "16px 0 0 16px",
                  },
                  "&:hover": {
                    borderColor: "#CBD5E1",
                    boxShadow:
                      "0 4px 24px rgba(15,23,42,0.08), 0 1px 4px rgba(15,23,42,0.04)",
                    transform: "translateY(-2px)",
                    bgcolor: "#FAFBFF",
                  },
                  "&:hover::before": {
                    opacity: 1,
                  },
                  "&:active": {
                    transform: "translateY(0px)",
                    boxShadow: "0 1px 6px rgba(15,23,42,0.06)",
                  },
                }}
              >
                {/* ── Top Row: Avatar + Name + Receipt + Shift Chip + Print Btn ── */}
                <Box
                  sx={{
                    display: "flex",
                    alignItems: "center",
                    gap: 2,
                    mb: { xs: 2, md: 2 },
                  }}
                >
                  {/* Avatar */}
                  <Avatar
                    src={s.photoUrl}
                    variant="rounded"
                    sx={{
                      width: { xs: 46, md: 52 },
                      height: { xs: 46, md: 52 },
                      borderRadius: "14px",
                      bgcolor: avatarColors.bg,
                      color: avatarColors.color,
                      border: `1.5px solid ${avatarColors.bg}`,
                      fontSize: "1.15rem",
                      fontWeight: 800,
                      flexShrink: 0,
                      boxShadow: `0 0 0 3px ${avatarColors.bg}`,
                    }}
                  >
                    {s.fullName?.[0]}
                  </Avatar>

                  {/* Name + Receipt */}
                  <Box sx={{ minWidth: 0, flex: 1 }}>
                    <p
                      style={{
                        margin: 0,
                        fontSize: "0.97rem",
                        fontWeight: 750,
                        color: "#0F172A",
                        overflow: "hidden",
                        textOverflow: "ellipsis",
                        whiteSpace: "nowrap",
                        letterSpacing: "-0.01em",
                      }}
                    >
                      {s.fullName}
                    </p>
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "center",
                        gap: 1,
                        mt: 0.3,
                        flexWrap: "wrap",
                      }}
                    >
                      <Box
                        sx={{
                          display: "inline-flex",
                          alignItems: "center",
                          gap: 0.4,
                          px: 1,
                          py: 0.2,
                          bgcolor: "#F8FAFC",
                          borderRadius: "6px",
                          border: "1px solid #E2E8F0",
                        }}
                      >
                        <BadgeOutlined
                          sx={{ fontSize: 11, color: "#94A3B8" }}
                        />
                        <span
                          style={{
                            fontSize: "0.72rem",
                            fontWeight: 700,
                            color: "#475569",
                            letterSpacing: "0.03em",
                          }}
                        >
                          {s.receiptNumber}
                        </span>
                      </Box>
                      {s.mobile && (
                        <Box
                          sx={{
                            display: "inline-flex",
                            alignItems: "center",
                            gap: 0.4,
                          }}
                        >
                          <PhoneOutlined
                            sx={{ fontSize: 11, color: "#94A3B8" }}
                          />
                          <span
                            style={{ fontSize: "0.72rem", color: "#64748B" }}
                          >
                            {s.mobile}
                          </span>
                        </Box>
                      )}
                    </Box>
                  </Box>

                  {/* Shift Chip */}
                  {s.shift && (
                    <Chip
                      label={formatShift(s.shift)}
                      size="small"
                      sx={{
                        bgcolor: shiftColors.bg,
                        color: shiftColors.color,
                        border: `1px solid ${shiftColors.border}`,
                        fontSize: "0.7rem",
                        fontWeight: 700,
                        height: 24,
                        borderRadius: "8px",
                        flexShrink: 0,
                        display: { xs: "none", sm: "inline-flex" },
                      }}
                    />
                  )}

                  {/* Print Button */}
                  <Tooltip title="Print Receipt">
                    <IconButton
                      size="small"
                      onClick={(e) => handleReprint(e, s)}
                      disabled={isReprintLoading}
                      sx={{
                        bgcolor: "#EFF6FF",
                        color: "#2563EB",
                        border: "1px solid #DBEAFE",
                        width: 34,
                        height: 34,
                        flexShrink: 0,
                        transition: "all 0.15s ease",
                        "&:hover": {
                          bgcolor: "#2563EB",
                          color: "#fff",
                          borderColor: "#2563EB",
                          transform: "scale(1.08)",
                        },
                      }}
                    >
                      {isReprintLoading ? (
                        <CircularProgress size={14} color="inherit" />
                      ) : (
                        <PrintOutlined sx={{ fontSize: 16 }} />
                      )}
                    </IconButton>
                  </Tooltip>
                </Box>

                {/* ── Info Section: 2 rows ── */}
                <Box sx={{ pt: 1.5, borderTop: "1px solid #F1F5F9" }}>
                  {/* Row 1: 4-column label+value grid */}
                  <Box
                    sx={{
                      display: "grid",
                      gridTemplateColumns: {
                        xs: "1fr 1fr",
                        sm: "repeat(4, 1fr)",
                        md: "repeat(4, 1fr)",
                      },
                      gap: { xs: 2, md: 0 },
                      mb: 1.5,
                    }}
                  >
                    {/* Year */}
                    <Box sx={{ px: { md: 0 }, pr: { md: 2 } }}>
                      <p
                        style={{
                          margin: 0,
                          fontSize: "0.64rem",
                          fontWeight: 700,
                          color: "#94A3B8",
                          textTransform: "uppercase",
                          letterSpacing: "0.08em",
                          display: "flex",
                          alignItems: "center",
                          gap: 3,
                          marginBottom: 3,
                        }}
                      >
                        <SchoolOutlined style={{ fontSize: 11 }} /> Year
                      </p>
                      <p
                        style={{
                          margin: 0,
                          fontSize: "0.85rem",
                          fontWeight: 700,
                          color: "#0F172A",
                        }}
                      >
                        {YEAR_LABEL[s.year] || s.year || "—"}
                      </p>
                    </Box>

                    {/* Department */}
                    <Box
                      sx={{
                        borderLeft: { md: "1px solid #F1F5F9" },
                        pl: { md: 2 },
                        pr: { md: 2 },
                      }}
                    >
                      <p
                        style={{
                          margin: 0,
                          fontSize: "0.64rem",
                          fontWeight: 700,
                          color: "#94A3B8",
                          textTransform: "uppercase",
                          letterSpacing: "0.08em",
                          marginBottom: 3,
                        }}
                      >
                        Department
                      </p>
                      <p
                        style={{
                          margin: 0,
                          fontSize: "0.85rem",
                          fontWeight: 500,
                          color: "#334155",
                        }}
                      >
                        {s.department?.label || "—"}
                      </p>
                    </Box>

                    {/* Pickup Point */}
                    <Box
                      sx={{
                        borderLeft: { md: "1px solid #F1F5F9" },
                        pl: { md: 2 },
                        pr: { md: 2 },
                      }}
                    >
                      <p
                        style={{
                          margin: 0,
                          fontSize: "0.64rem",
                          fontWeight: 700,
                          color: "#94A3B8",
                          textTransform: "uppercase",
                          letterSpacing: "0.08em",
                          display: "flex",
                          alignItems: "center",
                          gap: 3,
                          marginBottom: 3,
                        }}
                      >
                        <DirectionsBusOutlined style={{ fontSize: 11 }} />{" "}
                        Pickup Point
                      </p>
                      <p
                        style={{
                          margin: 0,
                          fontSize: "0.85rem",
                          fontWeight: 500,
                          color: "#334155",
                        }}
                      >
                        {s.pickupPoint?.label || "—"}
                      </p>
                    </Box>

                    {/* Semester */}
                    <Box
                      sx={{
                        borderLeft: { md: "1px solid #F1F5F9" },
                        pl: { md: 2 },
                      }}
                    >
                      <p
                        style={{
                          margin: 0,
                          fontSize: "0.64rem",
                          fontWeight: 700,
                          color: "#94A3B8",
                          textTransform: "uppercase",
                          letterSpacing: "0.08em",
                          marginBottom: 3,
                        }}
                      >
                        Semester
                      </p>
                      <p
                        style={{
                          margin: 0,
                          fontSize: "0.85rem",
                          fontWeight: 500,
                          color: "#334155",
                        }}
                      >
                        {s.semester || "—"}
                      </p>
                    </Box>
                  </Box>

                  {/* Row 2: Date tags */}
                  <Box
                    sx={{
                      display: "flex",
                      alignItems: "center",
                      gap: 1,
                      pt: 1.2,
                      borderTop: "1px dashed #F1F5F9",
                    }}
                  >
                    {/* Date of Approval */}
                    <Box
                      sx={{
                        display: "inline-flex",
                        alignItems: "center",
                        gap: 0.6,
                        px: 1.2,
                        py: 0.4,
                        bgcolor: "#F0FDF4",
                        border: "1px solid #BBF7D0",
                        borderRadius: "8px",
                      }}
                    >
                      <CalendarTodayOutlined
                        sx={{ fontSize: 11, color: "#15803D" }}
                      />
                      <span
                        style={{
                          fontSize: "0.67rem",
                          fontWeight: 600,
                          color: "#86EFAC",
                          textTransform: "uppercase",
                          letterSpacing: "0.06em",
                        }}
                      >
                        Approved
                      </span>
                      <span
                        style={{
                          fontSize: "0.82rem",
                          fontWeight: 700,
                          color: "#15803D",
                        }}
                      >
                        {fmtDate(s.approvedAt)}
                      </span>
                    </Box>

                    {/* Valid Up To */}
                    <Box
                      sx={{
                        display: "inline-flex",
                        alignItems: "center",
                        gap: 0.6,
                        px: 1.2,
                        py: 0.4,
                        bgcolor: "#EFF6FF",
                        border: "1px solid #BFDBFE",
                        borderRadius: "8px",
                      }}
                    >
                      <EventAvailableOutlined
                        sx={{ fontSize: 11, color: "#2563EB" }}
                      />
                      <span
                        style={{
                          fontSize: "0.67rem",
                          fontWeight: 600,
                          color: "#93C5FD",
                          textTransform: "uppercase",
                          letterSpacing: "0.06em",
                        }}
                      >
                        Valid to
                      </span>
                      <span
                        style={{
                          fontSize: "0.82rem",
                          fontWeight: 700,
                          color: "#2563EB",
                        }}
                      >
                        {fmtDate(s.validityDate)}
                      </span>
                    </Box>
                  </Box>
                </Box>
              </Box>
            );
          })
        )}
      </Box>

      {/* Load More Footer */}
      {!loading && hasMore && (
        <Box sx={{ mt: 3, textAlign: "center" }}>
          <Box
            onClick={handleLoadMore}
            sx={{
              display: "inline-flex",
              alignItems: "center",
              gap: 1,
              px: 4,
              py: 1.2,
              borderRadius: "12px",
              border: "1.5px solid #E2E8F0",
              bgcolor: "#fff",
              color: "#2563EB",
              fontWeight: 700,
              fontSize: "0.85rem",
              cursor: "pointer",
              transition: "all 0.15s ease",
              "&:hover": {
                bgcolor: "#EFF6FF",
                borderColor: "#BFDBFE",
              },
            }}
          >
            {loadingMore ? (
              <CircularProgress size={14} color="inherit" />
            ) : null}
            {loadingMore
              ? "Loading..."
              : `Load More Students (${totalCount - students.length} remaining)`}
          </Box>
        </Box>
      )}

      {/* Modals */}
      <ReceiptDialog
        open={receiptOpen}
        receiptData={receiptData}
        onClose={() => {
          setReceiptOpen(false);
          setReceiptData(null);
        }}
      />
      <EditApprovedStudentModal
        open={editOpen}
        student={editStudent}
        onClose={() => {
          setEditOpen(false);
          setEditStudent(null);
        }}
        onSaved={handleEditSaved}
      />
    </Box>
  );
}

// ── InfoItem: compact inline label + value ─────────────────────────
function InfoItem({ icon, label, value, bold }) {
  return (
    <Box sx={{ display: "inline-flex", alignItems: "baseline", gap: 0.5 }}>
      {icon && (
        <Box
          sx={{
            display: "inline-flex",
            alignItems: "center",
            alignSelf: "center",
          }}
        >
          {icon}
        </Box>
      )}
      <span
        style={{
          fontSize: "0.7rem",
          fontWeight: 600,
          color: "#94A3B8",
          textTransform: "uppercase",
          letterSpacing: "0.07em",
          marginRight: 3,
        }}
      >
        {label}
      </span>
      <span
        style={{
          fontSize: "0.82rem",
          fontWeight: bold ? 700 : 500,
          color: bold ? "#0F172A" : "#334155",
          overflow: "hidden",
          textOverflow: "ellipsis",
          whiteSpace: "nowrap",
          maxWidth: "160px",
          display: "inline-block",
        }}
      >
        {value}
      </span>
    </Box>
  );
}

// ── Dot separator ──────────────────────────────────────────────────
function Dot() {
  return (
    <Box
      sx={{
        width: 3,
        height: 3,
        borderRadius: "50%",
        bgcolor: "#CBD5E1",
        flexShrink: 0,
        display: { xs: "none", md: "block" },
      }}
    />
  );
}
